# Generated by Django 5.1.6 on 2025-03-01 10:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_order_user_product_user_rating_user_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='main_image',
            field=models.ImageField(default=1, help_text='Фото которое будет отображаться на обложке обьявления', upload_to='media/main_covers', verbose_name='Главное фото'),
            preserve_default=False,
        ),
    ]
