# Generated by Django 5.1.6 on 2025-03-12 17:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_order_check_image_order_status_order_update_date_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='order',
            options={'verbose_name': 'Заявка на оплату', 'verbose_name_plural': 'Заявки на оплаты'},
        ),
    ]
