# Generated by Django 5.1.6 on 2025-03-16 19:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_payment'),
    ]

    operations = [
        migrations.AddField(
            model_name='paymentrequest',
            name='total_price',
            field=models.PositiveIntegerField(default=1, verbose_name='Сумма'),
            preserve_default=False,
        ),
    ]
