# Generated by Django 5.1.6 on 2025-03-17 15:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0010_paymentrequest_total_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='total_price',
            field=models.PositiveIntegerField(default=1, verbose_name='Сумма'),
            preserve_default=False,
        ),
    ]
