# Generated by Django 5.1.6 on 2025-03-13 08:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_otp'),
    ]

    operations = [
        migrations.AddField(
            model_name='myuser',
            name='is_2fa_enabled',
            field=models.BooleanField(default=False, verbose_name='Включить 2FA'),
        ),
    ]
