# Generated by Django 5.1.6 on 2025-03-16 15:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_myuser_is_2fa_enabled'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='myuser',
            name='is_2fa_enabled',
        ),
        migrations.AddField(
            model_name='myuser',
            name='is_otp',
            field=models.BooleanField(default=False, verbose_name='Включить'),
        ),
    ]
